services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: